# Generated by Django 4.1.1 on 2022-09-23 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('map_image', models.ImageField(upload_to='images/')),
                ('game', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pixel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('agent', models.CharField(max_length=100)),
                ('approved', models.BooleanField(default=False)),
                ('sent_by', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='videos/')),
                ('game_map', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='astarix.gamemap')),
            ],
        ),
    ]
