# Generated by Django 4.1.1 on 2022-09-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astarix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixel',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='sent_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
